services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fingo
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db: {}
